#!/bin/sh
set -e

# Run as current user
if [ ! -z "$ASUSER" ]; then
    usermod -u $ASUSER developer
fi

# Ensure /.composer exists and is writable
if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer

if [ "$1" = "php-fpm" ]; then
    exec "$@"
    exit $?
fi

exec su-exec $ASUSER "$@"
